name: Github Pages Deploy

on:
  push:
    branches:
      - "main"


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.14.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: dist/event-management-portal-frontend
